= Crux Pull

Pulling data out of https://opencrux.com[Crux].

== Introduction

Crux is unbundled. This allows us to query it with any query language we like.

'Pull' queries, such as GraphQL and https://edn-query-language.org[EQL] are very
useful in certain domains, such as for user-interfaces.

== Getting started


[source,,subs="quotes"]
----
$ *clj -A:dev*
Clojure 1.10.1
user=> *(dev)*
[Edge] Loading Clojure code, please wait...
[Edge] Enter (go) to start the dev system

dev=> *(go)*
15:37:32.601 WARN  crux.kv.memdb [main]
Using sync? on MemKv has no effect. Persistence is disabled.
[Edge] Now make code changes, then enter (reset) here
:initiated

_Upon changes, reset the system with 'reset'_
dev> *(reset)*
----


== Testing

Run the tests with make

[source,,subs="quotes"]
----
$ *make test*
----

== Logic flow

=== Start the system, including a web-server

An integrant system is configured in `test/config.edn`.

A Jetty Ring web-server is started on port 8080.

See link:tree/master/test/crux/pull/server.clj[]

=== Respond with GraphiQL on request to `/`

HTTP requests to http://localhost:8080/[] elicit a response containing the HTML
of the GraphiQL tool.

=== Handle initial GraphqL introspection query at `/graphql`

==== Parse GraphQL query

TODO

==== Extract types from EQL 'schema'

TODO

==== Respond over HTTP with data on types

TODO

== References

EQL:: https://edn-query-language.org

GraphQL:: https://graphql.org
